version: '3.8'
services:
  app:
    container_name: php-apache
    image: tsania/uas
    depends_on:
      - db
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 8000:80
    networks:
      - backend

  db:
    container_name: db
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db_karyawan
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db:/var/lib/mysql
      - ./db_karyawan.sql:/docker-entrypoint-initdb.d/db_karyawan.sql
    networks:
      - backend

volumes:
    db:

#Docker Networks
networks:
  backend:
    name: backend-networks
    ipam: 
      driver: default
      config:
        - subnet: 172.20.0.0/24